# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4255b989d64445d4ef6108ee3d84dafbe175b20ced2901aacaa0ee590afc66a637f78036171dbb27a3f14868a23fba52f4d1d67a40e5cb68c7483c0b53722699

test:
  secret_key_base: b41b1dedcd7dc4a24dadb0904afa93f5c692c33b07f69f4f344868b70f82693c750ef102aa66a0ddcfb7ce6c2fc41e987c830f18eaa1462193febc41c9aa2979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
